# Generated by Django 4.2.13 on 2024-09-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Contact',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
    ]
