# Generated by Django 4.2.13 on 2024-09-05 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_contactus_contact_userprofilemodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='vip_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='会员结束时间'),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='vip_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='会员开通时间'),
        ),
        migrations.CreateModel(
            name='VipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='激活码')),
                ('type', models.IntegerField(default=1, verbose_name='类型')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('active_time', models.DateTimeField(blank=True, null=True, verbose_name='激活时间')),
                ('active_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='激活用户')),
            ],
            options={
                'verbose_name': '会员激活码',
                'verbose_name_plural': '会员激活码',
                'db_table': 'vip_code',
            },
        ),
    ]
