# Generated by Django 4.2.13 on 2024-09-06 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chapter',
            table='course_chapter',
        ),
    ]
