# Generated by Django 4.2.13 on 2024-09-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='desc',
            field=models.TextField(verbose_name='分类描述'),
        ),
    ]
