# Generated by Django 4.2.13 on 2024-09-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_coursecategory_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.TextField(verbose_name='课程描述'),
        ),
    ]
