# Generated by Django 4.2.13 on 2024-08-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.CharField(default='cover_default.jpg', max_length=255),
        ),
    ]
