# Generated by Django 4.2.13 on 2024-09-30 16:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_desc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CourseComment',
        ),
        migrations.AlterModelTable(
            name='coursecomment',
            table='course_comment',
        ),
    ]
